on:
  push:
    branches:
      - $default-branch
    paths:
      - "**.go"
      - "go.mod"
  pull_request:
    branches:
      - "**"
    paths:
      - "**.go"
      - "go.mod"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write

name: tests
jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x, 1.21.x, 1.22.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: '**/go.sum'
      - run: # test commands
        if: (github.event_name != 'workflow_dispatch')

  sast:
    runs-on: ubuntu-latest
    needs: tests
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: teler-sh/actions/dependency-review@dev
        if: (github.event_name == 'push')
      - uses: teler-sh/actions/golangci-lint@dev
      - uses: teler-sh/actions/semgrep@dev
      - uses: teler-sh/actions/bearer@dev
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: teler-sh/actions/codeql@dev
        with:
          lang: go
